# Generated by Django 3.2.8 on 2021-10-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vest_weight', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeightTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercised_on', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(default='weight_training', editable=False, max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='aida.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WeightExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aida.exercise')),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(default='weight_exercise', editable=False, max_length=25)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aida.weighttraining')),
            ],
            bases=('aida.exercise',),
        ),
    ]
