# Generated by Django 3.2.8 on 2021-10-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='training',
            new_name='workout',
        ),
    ]
