# Generated by Django 3.2.8 on 2021-10-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('weight', 'Weight'), ('undefined', 'Undefined')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, choices=[('cardio', 'Cardio Workout'), ('weight', 'Weight Workout')], max_length=255, null=True),
        ),
    ]
