# Generated by Django 3.2.8 on 2021-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='cardioset',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='weightset',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
