# Generated by Django 3.2.8 on 2021-10-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioset',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('min', 'minutes'), ('sec', 'seconds'), ('hour', 'hours')], max_length=10, null=True),
        ),
    ]
