# Generated by Django 3.2.8 on 2021-10-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'ordering': ['-measured_at'], 'verbose_name_plural': 'Blood pressure metrics'},
        ),
        migrations.AlterModelOptions(
            name='heartrate',
            options={'ordering': ['-measured_at'], 'verbose_name_plural': 'Heart rate metrics'},
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.PositiveSmallIntegerField(help_text='Enter diastolic value (the lower value)'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.PositiveSmallIntegerField(help_text='Enter the systolic value (the upper value)'),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='pulse',
            field=models.PositiveSmallIntegerField(help_text='Enter your hearts beats per minute'),
        ),
    ]
