# Generated by Django 3.2.8 on 2021-10-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0002_cardioset_time_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioset',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('min', 'Minutes'), ('sec', 'Seconds'), ('hour', 'Hours')], max_length=10, null=True),
        ),
    ]
