# Generated by Django 3.2.8 on 2021-10-13 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0003_auto_20211013_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_at', models.DateTimeField()),
                ('systolic', models.PositiveSmallIntegerField()),
                ('diastolic', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Blood pressure metrics',
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_at', models.DateTimeField()),
                ('pulse', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pulse metrics',
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awake_at', models.DateTimeField()),
                ('slept_at', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sleep metrics',
            },
        ),
        migrations.CreateModel(
            name='WeightSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('weight_unit', models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=10, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aida.exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardioSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('time_unit', models.CharField(blank=True, choices=[('min', 'Minutes'), ('sec', 'Seconds'), ('hour', 'Hours')], max_length=10, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aida.exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
