# Generated by Django 3.2.8 on 2021-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aida', '0003_alter_cardioset_time_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightset',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=10, null=True),
        ),
    ]
